// Mocks generated by Mockito 5.4.6 from annotations
// in foood/test/widget_test/lists_widget_tests.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:foood/helpers/shopping_list_manager.dart' as _i3;
import 'package:foood/models/shopping_list.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeShoppingList_0 extends _i1.SmartFake implements _i2.ShoppingList {
  _FakeShoppingList_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ShoppingListManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockShoppingListManager extends _i1.Mock
    implements _i3.ShoppingListManager {
  MockShoppingListManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.ShoppingList> get allLists =>
      (super.noSuchMethod(
            Invocation.getter(#allLists),
            returnValue: <_i2.ShoppingList>[],
          )
          as List<_i2.ShoppingList>);

  @override
  set activeList(_i2.ShoppingList? value) => super.noSuchMethod(
    Invocation.setter(#activeList, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> loadAllLists() =>
      (super.noSuchMethod(
            Invocation.method(#loadAllLists, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void setActiveList(_i2.ShoppingList? list) => super.noSuchMethod(
    Invocation.method(#setActiveList, [list]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i2.ShoppingList> createNewList(String? listName) =>
      (super.noSuchMethod(
            Invocation.method(#createNewList, [listName]),
            returnValue: _i4.Future<_i2.ShoppingList>.value(
              _FakeShoppingList_0(
                this,
                Invocation.method(#createNewList, [listName]),
              ),
            ),
          )
          as _i4.Future<_i2.ShoppingList>);

  @override
  _i4.Future<void> saveActiveList() =>
      (super.noSuchMethod(
            Invocation.method(#saveActiveList, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addNewItemToActiveList({
    required String? name,
    required String? units,
    required int? quantity,
    int? ordering,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addNewItemToActiveList, [], {
              #name: name,
              #units: units,
              #quantity: quantity,
              #ordering: ordering,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
